model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      custom_llm_provider: openai

# https://docs.litellm.ai/docs/observability/datadog
litellm_settings:
  success_callback: ["datadog_metrics", "datadog", "datadog_llm_observability", "datadog_cost_management"]
  failure_callback: ["datadog_metrics", "datadog"]
  service_callback: ["datadog"]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
